apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sushiweb-multiarch-build
  namespace: sushiweb-multiarch-build
spec:
  params:
  - name: GIT_REPO
    type: string
  - default: main
    name: GIT_REV
    type: string
  - name: IMAGE_NAME
    type: string
  - name: IMAGE_TAG
    type: string
  - default: .
    description: Path to the directory to use as context.
    name: CONTEXT
    type: string
  - default: ./Dockerfile
    description: 'Dockerfile name '
    name: DOCKERFILE
    type: string
  tasks:
  - name: build-ppc64le
    params:
    - name: pipeline-name
      value: sushiweb-build
    - name: pipeline-namespace
      value: sushiweb-build
    - name: pipeline-args
      value: --param GIT_REPO=$(params.GIT_REPO) --param GIT_REV=$(params.GIT_REV)
        --param IMAGE_NAME=$(params.IMAGE_NAME) --param IMAGE_TAG=$(params.IMAGE_TAG)-ppc64le
        --param CONTEXT=$(params.CONTEXT) --param DOCKERFILE=$(params.DOCKERFILE)
        --workspace name=workspace,claimName=sushiweb-build
    - name: openshift-server-url
      value: https://api.opal.edu.ihost.com:6443
    - name: openshift-token-secret
      value: opal-pipeline-starter
    taskRef:
      kind: Task
      name: execute-remote-pipeline
  - name: manifest
    params:
    - name: MANIFEST_FILE
      value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
    - name: IMAGES_LIST
      value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)-ppc64le $(params.IMAGE_NAME):$(params.IMAGE_TAG)-s390x $(params.IMAGE_NAME):$(params.IMAGE_TAG)-x86_64 '
    runAfter:
    - build-ppc64le
    - build-x86
    - build-s390x
    taskRef:
      kind: Task
      name: manifest
  - name: build-x86
    params:
    - name: pipeline-name
      value: sushiweb-build
    - name: pipeline-namespace
      value: sushiweb-build
    - name: openshift-server-url
      value: https://api.topaz.edu.ihost.com:6443
    - name: openshift-token-secret
      value: topaz-pipeline-starter
    - name: pipeline-args
      value: --param GIT_REPO=$(params.GIT_REPO) --param GIT_REV=$(params.GIT_REV)
        --param IMAGE_NAME=$(params.IMAGE_NAME) --param IMAGE_TAG=$(params.IMAGE_TAG)-x86_64
        --param CONTEXT=$(params.CONTEXT) --param DOCKERFILE=$(params.DOCKERFILE)
        --workspace name=workspace,claimName=sushiweb-build
    taskRef:
      kind: Task
      name: execute-remote-pipeline
  - name: build-s390x
    params:
    - name: pipeline-name
      value: sushiweb-build
    - name: pipeline-namespace
      value: sushiweb-build
    - name: pipeline-args
      value: --param GIT_REPO=$(params.GIT_REPO) --param GIT_REV=$(params.GIT_REV)
        --param IMAGE_NAME=$(params.IMAGE_NAME) --param IMAGE_TAG=$(params.IMAGE_TAG)-s390x
        --param CONTEXT=$(params.CONTEXT) --param DOCKERFILE=$(params.DOCKERFILE)
        --workspace name=workspace,claimName=sushiweb-build
    - name: openshift-server-url
      value: https://api.saphir.edu.ihost.com:6443
    - name: openshift-token-secret
      value: saphir-pipeline-starter
    taskRef:
      kind: Task
      name: execute-remote-pipeline
