apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sushiweb-multiarch-build
  generateName: sushiweb-multiarch-build-
  namespace: sushiweb-multiarch-build
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/schabrolles/sushiweb'
    - name: GIT_REV
      value: master
    - name: IMAGE_NAME
      value: quay.io/schabrolles/sushi-demo
    - name: IMAGE_TAG
      value: mac
    - name: CONTEXT
      value: .
    - name: DOCKERFILE
      value: ./Dockerfile
  serviceAccountName: pipeline
  pipelineRef:
    name: sushiweb-multiarch-build
  taskRunSpecs:
    # Build the amd64 image on dedicated amd64 hardware
    - pipelineTaskName: build-x86
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
    # Build the arm64 image on dedicated arm64 hardware
    - pipelineTaskName: build-ppc64le
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: ppc64le
  workspaces:
    # Disk Volumes
    - name: ws
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 2Gi
