apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sushiweb-multiarch-build
  namespace: sushiweb-multiarch-build
spec:

  params:
    - name: GIT_REPO
      type: string
    - default: main
      name: GIT_REV
      type: string
    - name: IMAGE_NAME
      type: string
    - name: IMAGE_TAG
      type: string
    - default: .
      description: Path to the directory to use as context.
      name: CONTEXT
      type: string
    - default: ./Dockerfile
      description: 'Dockerfile name '
      name: DOCKERFILE
      type: string
  
  workspaces:
    - name: ws
  
  tasks:

    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REV)
      workspaces:
        - name: output
          workspace: ws


    - name: build-x86
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: ws
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)-x86_64'
        - name: ARCH
          value: amd64
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT)
        - name: BUILD_EXTRA_ARGS
          value: "--no-cache"
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci

    - name: build-ppc64le
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: ws
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)-ppc64le'
        - name: ARCH
          value: ppc64le
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT)
        - name: BUILD_EXTRA_ARGS
          value: "--no-cache"
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci

    - name: multiarch-manifest
      params:
        - name: MANIFEST_FILE
          value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
        - name: IMAGES_LIST
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)-ppc64le $(params.IMAGE_NAME):$(params.IMAGE_TAG)-x86_64 '
      runAfter:
        - build-ppc64le
        - build-x86
      taskRef:
        kind: Task
        name: manifest

