apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: "2022-04-24T14:10:40Z"
  generation: 1
  managedFields:
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:params: {}
        f:steps: {}
    manager: Mozilla
    operation: Update
    time: "2022-04-24T14:10:40Z"
  name: podman
  namespace: sushiweb-multiarch-build
  resourceVersion: "337303929"
  uid: 34e71b9f-d5bf-4466-a493-3df37b69fb3f
spec:
  params:
  - name: podmanArgs
    type: string
  steps:
  - command:
    - /bin/bash
    - -c
    - podman
    - $(inputs.params.podmanArgs)
    image: quay.io/containers/podman
    name: ""
    resources: {}
