apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: manifest
  namespace: sushiweb-multiarch-build
spec:
  params:
    - description: >-
        name of the manifest image to be pushed to the target registry
        (quay.io/dir/manifest:tag)
      name: MANIFEST_FILE
      type: string
    - description: >-
        name of the images to be referenced by the manifest file separated by
        sapce (quay.io/dir/image:tag)
      name: IMAGES_LIST
      type: string
  steps:
    - image: quay.io/containers/podman
      name: manifest
      resources: {}
      script: |
        echo "create manifest"
        podman manifest create mylist
        echo

        for image in $(params.IMAGES_LIST); do 
          echo "add $image"
          podman manifest add mylist $image
        done

        echo
        echo "push manifest $(params.MANIFEST_FILE)"
        podman manifest push mylist docker://$(params.MANIFEST_FILE) 
      securityContext:
        capabilities:
          add:
            - SETFCAP
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - emptyDir: {}
      name: varlibcontainers
