apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sushiweb-build
  namespace: sushiweb-build
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: scale-hmcs-fileset
  volumeMode: Filesystem
