apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: manifest
spec:
  params:
    - name: MANIFEST_FILE
      type: string
      description: name of the manifest image to be pushed to the target registry (quay.io/dir/manifest:tag)
    - name: IMAGES_LIST
      type: string
      description: name of the images to be referenced by the manifest file separated by sapce (quay.io/dir/image:tag)
  steps:
    - script: |
        podman manifest create mylist && \
        for image in $(params.IMAGES_LIST); do podman manifest add mylist \$image; done &&\
        podman manifest push docker:\/\/$(params.MANIFEST_FILE) 
      image: quay.io/containers/podman
      name: 'manifest'
      resources: {}
      securityContext:
        capabilities:
          add:
            - SETFCAP
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - emptyDir: {}
      name: varlibcontainers
